name: Create-Release-Tag

on:
  [workflow_call]

jobs:
  create-tag-master:
    runs-on: [self-hosted, Linux, robby]
    if: ${{ github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v3
      - uses: rlib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Get Version from DESCRIPTION
        id: get_version
        run: |
          echo "TAG=$(awk '/Version/' DESCRIPTION | awk -F': ' '{print "v" $2}')" >> $GITHUB_OUTPUT

      - uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with: 
          tag: ${{ steps.get_version.TAG }}
      
      - uses: rickstaa/action-create-tag@v1
        if: steps.checkTag.outputs.exists == 'false'
        id: "tag_create"
        with:
          tag: ${{ steps.get_version.TAG }}
          tag_exists_error: true
          message: "Release ${{ steps.get_version.TAG }}"
  
  create-tag-dev:
    runs-on: [self-hosted, Linux, robby]
    if: ${{ github.ref_name == 'dev' }}
    steps:
      - uses: actions/checkout@v3
      - uses: rlib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Get Version from DESCRIPTION
        id: get_version
        run: |
          echo "TAG=$(awk '/Version/' DESCRIPTION | awk -F': ' '{print "v" $2 "-beta"}')" >> $GITHUB_OUTPUT

      - uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with: 
          tag: ${{ steps.get_version.TAG }}
      
      - uses: rickstaa/action-create-tag@v1
        if: steps.checkTag.outputs.exists == 'false'
        id: "tag_create"
        with:
          tag: ${{ steps.get_version.TAG }}
          tag_exists_error: true
          message: "Release ${{ steps.get_version.TAG }}"



